### ISSUE TITLE
Investigate issue with Azure Functions integration when promises are returned

### ISSUE THREAD

**Issue by hectorhdzg** [microsoft/ApplicationInsights-node.js#1063]
Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/652#issuecomment-1382897947

**Comment by paulsmithkc** [comment]
Can we get some more clarity on what this issue is, and what the available workarounds are?

This bug took down a business critical system today.

**Comment by chuanqisun** [comment]
(originally posted in https://github.com/Azure/azure-functions-nodejs-worker/issues/652)

+1 This is blocking us from upgrading to 2.4, which contains important security fixes from https://github.com/microsoft/ApplicationInsights-node.js/pull/1057 

In our case, calling `appInsights.setup()` would cause Azure Function runtime to throw the error `Choose either to return a promise or call 'done'.  Do not use both in your script.` So maybe investigate the call graph of `setup()`?

We are using node 16 LTS but I believe the underlying issue is the same. I hope this information helps. If you want repro, feel free to contact me via Microsoft teams DM


```
ENV
Core Tools Version:       4.0.4895 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.13.0.19486
Node:                     v16.19.0
```
