### ISSUE TITLE
Dependency requests not logged on node 18 with fetch API

### ISSUE THREAD

**Issue by arisewanggithub** [microsoft/ApplicationInsights-node.js#1295]
We upgraded to node 18 and find that requests telemetry work but dependency telemetry is not logged (with latest version 2.9.5. or with an old version 2.5.2). With node 16, it works well. Is it by design that node 18 and above won't work with appInsights?

**Comment by JacksonWeber** [comment]
@arisewanggithub Some further information would be helpful here. Can you provide the `package.json` for the application you're instrumenting and taking a look at the code where you expect dependency telemetry to be generated would be helpful too.

**Comment by arisewanggithub** [comment]
@JacksonWeber, I've sent you the package.json in private. Please let me know if you need anything else to troubleshoot.

**Comment by JacksonWeber** [comment]
@arisewanggithub I'm sorry, but I'm not quite sure where you sent the `package.json`. What method did you use to send it to me?

**Comment by arisewanggithub** [comment]
@JacksonWeber , I sent the files to your corp email. I also pinged you on teams. Please let me know if you didn't receive it.

**Comment by cristobal** [comment]
Works fine here, not sure if you had the same problem that we had, we use fastify and doing the following solved our problenm.


### Old code:
```ts
const app = fastify(fastifyOptions);
...
configureApplicationInsights();
```

### New Code:
```ts
// important configure application insights must be run before calling fastify(...);
configureApplicationInsights();

const app = fastify(fastifyOptions);
...
```

## The issue at hand
One needs to initialize application insights client before one initializes the server, otherwise the `http.createServer()` will be called without the application insights code have made and auto collector and wrapper arround `http.createServer` [here](https://github.com/microsoft/ApplicationInsights-node.js/blob/2b686622a04cc554ba72f9ec2a393afb1c6dd7c5/AutoCollection/HttpRequests.ts#L130-L181)

Seems like the changes in the code happened about 6 months ago, at some point we stopped tracking http requests when update the application insights package.

**Comment by arisewanggithub** [comment]
@cristobal , thanks for the reply. But that doesn't look like to be the cause of my issue. Also, in my case, request telemetry works. What is broken is dependency telemetry. And for the change you quoted, it's for request telemetry, not for dependency telemetry. So, it should be irrelevant, IMHO.

**Comment by JacksonWeber** [comment]
Closing this issue as auto instrumentation of the fetch API is not supported. Thank you for your report.

**Comment by arisewanggithub** [comment]
A summary of what happened. From node 18, node.js has a native implementation of the fetch API. In node 16, node-fetch was used and app insights still supports it. But app insights doesn't support this native implementation of the fetch API. And in node 18, the native fetch is used by default. That's why the Dependency telemetry breaks. A workaround is to force to use node-fetch in node 18.
