### ISSUE TITLE
Lose a lot of data using applicationinsights npm

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/ApplicationInsights-node.js#159]
I have lost user data about half a month using applicationinsights npm 0.15.x due to [Force HTTPS](https://azure.microsoft.com/en-us/updates/application-insights-telemetry-data-now-requires-https-with-shutdown-of-http-data-collectors/). Any way we could get the data back? And also, since my app is a desktop app, though I have release a new version, many users still use the old version. We are still losing data from thousands of users!

**Comment by kamilszostak** [comment]
I'm sorry to hear that you lost your telemetry. The Force HTTPS change was required for Application Insights to reach general availability and step out of the preview phase. Due to security reasons, we can no longer support the old http endpoint.

Unfortunately, there it is not possible to fix it without a code change. Telemetry collection backend returns 307 when you send data over http and it redirects to https url. Node.js doesn't automatically handle the redirect response codes and won't resend the data, so without a code change in your application, it's impossible to fix this. 

We are not expecting any breaking changes in the near future, but please subscript to https://github.com/Microsoft/ApplicationInsights-Announcements to get all announcements.
