### ISSUE TITLE
Better differentiate Client and Server requests

### ISSUE THREAD

**Issue by joshgav** [Microsoft/ApplicationInsights-node.js#225]
In a nutshell: ClientRequests are AppInsights Dependency items and should be more differentiated from ServerRequests which are AppInsights Request items.

`AutoCollection/ClientRequests.ts` to a significant degree conflates outgoing HTTP requests, which are AppInsights RemoteDependency items, with incoming HTTP requests, which are AppInsights Request items. In particular, both derive from `RequestParser` and both are named `*Request`.

It would be clearer if ClientRequests was renamed to ClientDependencies or HttpDependencies and  was derived from Dependency-related base classes rather than RequestParser. This would more clearly differentiate these Dependency items from Request items.

This is particularly helpful when reasoning about correlation. Incoming HTTP requests may be coming from another AppInsights-instrumented service and so our local service looks for several headers in the incoming request to add to its new Request item for correlation. Outgoing HTTP requests are RemoteDependency items and can include headers from the local client and root Request which the remote receiver can use for further correlation in the Request item it will create.

That is, a local Request is a RemoteDependency of the source, calling service; and a local RemoteDependency is a Request in the target, called service.

I've prepared a PR implementing the above suggested changes and will submit shortly.

**Comment by AlexBulankou** [comment]
To summarize the file renaming that is proposed to happen as part of this item:
1. AutoCollection/ClientRequestParser->AutoCollection/HttpDependencyParser
2. AutoCollection/ClientRequests -> AutoCollection/HttpDependencies
3. AutoCollection/ServerRequestParser -> AutoCollection/HttpRequestParser
4. AutoCollection/ServerRequests -> AutoCollection/HttpRequests

@OsvaldoRosado, @joshgav  Is that all? Rather than trying to merge Josh's original PR, might be easier to start again on the latest version and limit the changes to just this renaming.
