### ISSUE TITLE
Tracked exceptions not showing up in portal

### ISSUE THREAD

**Issue by itilitymaarten** [Microsoft/ApplicationInsights-node.js#247]
I've added the insights sdk to my code in order to attempt to track errors in my code for function apps. I can't use the default method of tracking failures for function apps (passing the error to `context.done(error)`), because that interrupts the HTTP response the function is supposed to give.

However, the exceptions do not show up in my insights instance. I assume the configuration is correct, since my custom events are showing up (although not associated with the actual request...is that supposed to happen?)

The test function I'm using:
```
module.exports = function (context, myTimer) {
    const appInsights = require("applicationinsights");
    appInsights.setAutoDependencyCorrelation(true);
    const client = appInsights.getClient();
    client.trackException(new Error("handled exceptions can be logged with this method"));
    client.trackEvent('custom event');

    context.log('JavaScript timer trigger function ran!');   
    context.done();
};
```

I don't know whether this is a bug in the SDK or in the portal. Errors passed to `context.done()` are properly marked as exceptions in the portal.

**Comment by OsvaldoRosado** [comment]
In a quick test against the latest version of the SDK, this small sample seems to work
```
var appInsights = require("applicationinsights");
appInsights.setAutoDependencyCorrelation(true);
var client = appInsights.getClient("ikey");
client.trackException(new Error("handled exceptions can be logged with this method"));
```

Perhaps you are running into a problem with your function app ending before the telemetry is sent? You can try using this instead of `context.done()` : `client.sendPendingData(()=> context.done())`
This will ensure you don't end the request until all pending telemetry is sent.

As for custom events being associated with your request. In ideal circumstances they should, but there are cases where we can't make correlation work (depending on what libraries you have in your system). For this simple example, you wouldn't have correlation because there is no server request (a req/res pair as generated by http.createServer) to make a request telemetry item to pair against. You might not make these directly in function apps, so #148 may be an issue as far as making request telemetry goes.

**Comment by itilitymaarten** [comment]
Thanks for your answer. First of all, a little context that I probably should have provided beforehand: I am running this code on Azure Functions, with the function app hooked up to Azure Insights as well.

Turns out exceptions were actually reaching insights, they were just not being associated with the request (just like events). I didn't think this was the problem since there wasn't a link to an events list in insights, but there was a link to exceptions. My apologies for that.

However, the association issue still stands. Perhaps this is not the proper thread to discuss it, but I'll just quickly put down my thoughts:
1. All traces (logging to the Azure Functions environment, exceptions logged by Azure Functions) are nicely put together and encapsulated in 1 "Insights request". So how come function calls to the SDK cannot be correlated? You know when a new client is created or a new instance has been setup (through the `getClient()` and `setup()` methods), so couldn't you treat any function call following as a single request, if no other method is available (i.e. no linking between request response objects)?
2. The issue you linked isn't entirely relevant, in my opinion. The author there is working with websockets, which implies some sort of persistence in the server, whereas in Azure Functions there is no persistence at all. I create a new instance of the SDK for every request.
3. Most of our Azure Functions are HTTP request based, with at least a request object available. The response object is probably in a different format from what you expect, since the full response is only generated by the Azure Functions runtime, after the Azure Function is finished. Could there be a way to emulate the request and response objects used by the SDK to recognize a request?

**Comment by OsvaldoRosado** [comment]
Thanks for the follow up! I linked #148 not because of similar situations, but because a resolution is the same - a way to track requests without a req/res pair.

As for why they cannot be correlated, we simply don't currently support automatic request collection for anything but the standard node server. Our correlation logic also correlates on requests, so without an automatically generated request context, or a manually generated one, you have no correlation.

Your suggested solution "so couldn't you treat any function call following as a single request, if no other method is available " is interesting, but presents some issues. For example, it is a perfectly valid use case to use this SDK outside of a server context (eg, a desktop app using node like VSCode or Electron apps in general). In this situation, assuming a correlation context merely from the lack of requests could be unexpected behavior.

This all said, because you have a single client for each request, you can work around this for your particular use case with a telemetry processor. Code like the following may work for you (make sure it's done before recording any telemetry):

```
var correlationId = Math.random().toString(36).substr(2, 10);
appInsights.client.addTelemetryProcessor((envelope) => {
     envelope.tags = envelope.tags || {};
     envelope.tags['ai.operation.id']  = correlationId;
});
```

We can look into creating an emulated response object if this workaround isn't working out right - though the real solution is for us to stop requiring one to make request telemetry.

**Comment by itilitymaarten** [comment]
@OsvaldoRosado that was a great suggestion! Using the invocationId from the function app (`context.bindingData.invocationId`), I've been able to link custom telemetry to output traces from the functions environment. Now everything's showing up in 1 beautiful set of debugging data. Thanks!

Is there any documentation on what other tags are available? And can I make my own? Assuming I can search on tags in insights (which I haven't been able to figure out...yet), it would even allow me to (manually) correlate events between requests.
Our function apps often send requests to eachother, so being able to track a whole chain throughout multiple apps using a tag or something similar would be amazing.

Do you know of any mechanism to do so?

**Comment by OsvaldoRosado** [comment]
Custom properties are indeed what you're looking for. These tags are searchable as well, but not intended for generic use. These tags get transformed into other fields by our backend and you can read their values in details blades (after clicking the ... at the end of the properties grid) in the portal, or as raw data to query against in Analytics.

As for this:
`Our function apps often send requests to eachother, so being able to track a whole chain throughout multiple apps using a tag or something similar would be amazing.`

This would work out of the box if we had proper request tracking working in Function apps. As a workaround, you can use custom properties to recreate something close like you mention and then correlate with some hand built Analytics queries (or Metrics Explorer may be able to do this too). 

If your function apps all share the same ikey, it may not be too difficult to do this in a way the Portal UI will recognize rather than rolling your own properties to do it. You'll need to use the tags ai.operation.id, as well as ai.operation.parentId, and have a way to pass this data across to your next function app (the SDK uses headers to do this). The idea is that the first function app determines the operationId that should be recorded in the telemetry for the entire chain, and then parentId is always set as the id of the current request. (There's more complication here if we had request telemetry - the parentId of the request telemetry should be the id of the service that called into it).

Once #148 is addressed, you wont need to do any of this - just call trackRequest at the beginning of your code. Then the Portal buttons for "all available telemetry for this root operation" or "external Application Insights dependency for this request" (if using different ikeys in each app) should show the data you're looking for.

**Comment by itilitymaarten** [comment]
I don't entirely follow you yet. So there are two tags: `ai.operation.id` and `ai.operation.parentId`. Currently, I'm setting `ai.operation.id` to the invocationId in order to correlate my own events, exceptions and tracing to the telemetry and tracing generated by the AF version of Azure Insights (the built in one). I am not using `operation.parentId` yet.

If I understand you correctly, I should now be setting `operation.parentId` to the invocationId, and set `operation.id` to an idea that identifies a set of requests across functions? To me, it makes more sense the other way around, given the names of the tags.

Also: should this be included in the documentation for the SDK(s)? It seems to me like this could help more people achieve what they want to do. I assume it's designed to be used by our code, not just the SDK (since you're suggesting it), so it would be useful if we didn't have to bother you guys in order to figure these things out. Will leave you more time to develop awesome features :)

**Comment by OsvaldoRosado** [comment]
>  To me, it makes more sense the other way around, given the names of the tags.

I understand the names are confusing and seem backwards :smile: Essentially id is the identifier for the entire operation (cross-service) and parentId is the identifier for the direct parent of the telemetry in question (since you have all dependencies, the parent is what the id of the request telemetry would have been if you could collect it - invocationId is a good stand-in)

Internally when you don't provide a parentId, we set it the same as operation.id, if that helps clarify why the code sample I gave before works.

These tags are documented in the endpoint docs for the service overall ( https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Docs/ContextTagKeys.md ). Their definitions are also included in our typescript typings. Look at the properties on `new appInsights.contracts.ContextTagKeys()` to see them.

We don't typically provide complete code examples on rolling your own for this because correlation gets surprisingly complex - especially when you want to coordinate cross-sdk or cross-ikey. In the majority of cases the SDK will handle this correctly for you. I suggested using these tags in your case because you happened to have a simple enough scenario where it would be the same amount of work as using your own custom properties.

Hope this helps!

**Comment by itilitymaarten** [comment]
The names do indeed seem backwards, but thanks to your explanation I understand them now.

I've got the correlation working the way I want to now, except for one small detail, but I don't believe that's fixable. I would like the requests in application insights to be associated with the operationId as well, however since they're generated by the Azure Functions runtime I have no way of accessing their tags. I assume this is impossible for me to fix right now, since I only know the operationId once my function run has already started.

However, thank you so much for your help. You've helped me understand a great deal and achieve what I wanted, within the bounds of possibility. I look forward to seeing what kind of improvements you guys bring in the next couple of months!

**Comment by IanKemp** [comment]
Schema now at: https://github.com/microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ContextTagKeys.bond
