### ISSUE TITLE
Developer mode?

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/ApplicationInsights-node.js#263]
What steps do I have to take if I want to use this library locally with VS code without having it wired into a live environment?

**Comment by OsvaldoRosado** [comment]
You can disable telemetry transmission by setting this flag (Shown here to set the default client, but the configuration object exists on clients made with `getClient` as well. Note that client objects do not share configuration with each other):

`appInsights.client.config.disableAppInsights = true;`

**Comment by OsvaldoRosado** [comment]
I'm closing this issue. Please feel free to re-open if the snippet above didn't answer your question!

**Comment by atrauzzi** [comment]
@OsvaldoRosado - It doesn't.  I'm not asking how to disable app insights.  I'm asking how to use it locally.

**Comment by OsvaldoRosado** [comment]
Sorry, I'm not sure I understand. Application Insights as a service runs in the cloud. You can send telemetry into it over the internet, but we don't offer an on-prem server you can send your telemetry to locally instead of our cloud service.

Your options for local use of this SDK are to continue allowing telemetry to leave the box and reach Application Insights, or disable telemetry transmission like I showed in the snippet above. 

If you're asking about an in-ide live telemetry browsing experience like we offer for .NET in Visual Studio, I don't believe that's compatible with the Node.js SDK or Visual Studio Code at this time.

Let me know if this helps!

**Comment by atrauzzi** [comment]
Any chance you can take it up with them?  Seems like it could be very helpful.

**Comment by AlexBulankou** [comment]
Please try AppInsights extension for VSCode (VisualStudioOnlineApplicationInsights.application-insights) and provide feedback to them
