### ISSUE TITLE
Specify resultCode when using trackDependency

### ISSUE THREAD

**Issue by glenjamin** [Microsoft/ApplicationInsights-node.js#286]
There doesn't seem to be any way to provide this, have I missed something or is this not supported in the current API?

**Comment by OsvaldoRosado** [comment]
A straightforward way to set this does seem to be missing. Thanks for catching this! Be aware, if you're using auto-collection of dependencies, the result code will still be tracked correctly.

For manual collection, you can store resultCode as a custom property, which will show up in the portal and analytics but not in the usual place you would expect resultCode. You can also combine this approach with a telemetry processor for a full workaround that places resultCode in the expected field rather than a custom property:

```
var appInsights = require("applicationinsights");

appInsights.client.addTelemetryProcessor((envelope) => {
    if (envelope.data.baseType === appInsights.contracts.DataTypes.REMOTE_DEPENDENCY) {
        // Instanceof check is optional. Provides type hinting for baseData
        let rdData = envelope.data.baseData; // May need to cast envelope.data to any if using TS
        if (rdData instanceof appInsights.contracts.RemoteDependencyData && rdData.properties.resultCode) {
            rdData.resultCode = rdData.properties.resultCode;
            delete rdData.properties.resultCode;
        }
    }
    return true;
});

appInsights.client.trackDependency("name", "commandName", 200, false, "HTTP", {resultCode: 404});

```
