### ISSUE TITLE
Relating traces and dependencies to incoming requests

### ISSUE THREAD

**Issue by glenjamin** [Microsoft/ApplicationInsights-node.js#287]
In the application insights UI, there's a section for dependency calls that were made as part of a request.

<img width="555" alt="screen shot 2017-07-11 at 12 16 32" src="https://user-images.githubusercontent.com/151272/28065979-f34a0ed2-6632-11e7-9604-26a5ebef7f4d.png">

Is this supposed to be populated automatically? I can see there's some zone code going on, do I need to enable this in some way?

Likewise it'd be good to be able to match my trace logs to the incoming request line.

**Comment by OsvaldoRosado** [comment]
This should be populated automatically, correlation is on by default in the latest version of this SDK. However, due to technical constraints in JavaScript we cannot always ensure correlation is possible (either gaps in Zone monkeypatching or our own diagnostic-channel patching). To get correlation working, you may need to use the `appInsights.wrapWithCorrelationContext` method to manually inform our SDK of places your code goes asynchronous.

**Comment by glenjamin** [comment]
Is there any way to debug this and figure out where the context is being lost?

I'm using promises quite a bit if that's relevant?


Specifically I added custom dependency tracking via query events to http://npm.im/knex which I'm using to talk to Azure SQL

**Comment by OsvaldoRosado** [comment]
Sorry for the delay in response here. Easiest way to debug this is to peek into the correlation context around where you suspect the context may get lost. In general, promises should be fine (although its possible some promise libraries have issues). Other libraries that go async are the usual culprit.

You can console log the output of `appInsights.getCorrelationContext().operation.id` at various points. Within a single request, this value should stay the same. If this correlation gets lost anywhere, you'll have found the problem area. Note that the correlation context has a few other fields you can use instead, including a custom property bag where you can set your own values.
