### ISSUE TITLE
Support disabling diagnostic channel configuration in code vs env var

### ISSUE THREAD

**Issue by jeffwilcox** [Microsoft/ApplicationInsights-node.js#288]
Hi,
I'd love to be able to set/configure diagnostic configuration settings in code instead of by using environment variables.

This is possible via configuration on the client for other features such as auto dependency tracking.

Happy to try and contribute, but wanted to log this in the meantime.

For example, to disable automatic diagnostic providers, you can set `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL ` to a value; it is then read in https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/AutoCollection/diagnostic-channel/initialization.ts#L6.

Would prefer to be able to follow a config syntax similar to the documented example:

```
    const instance = appInsights.setup(key)
      .setAutoCollectConsole(false)
      .setAutoCollectRequests(false)
      .setAutoCollectDiagnosticChannels(false); // my example, added
    client = instance.getClient(key);

```

Of course I could just set `process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = '1'` in code, but that feels a little messier.

**Comment by OsvaldoRosado** [comment]
@MSLaguana who can provide more details / confirmation.

I'm not a huge fan of this as env vars either, but it's the best solution we've found so far. The technical hurdle is that the monkey patching done in diagnostic channel is done at `require()` time for every library you call require on. In most setups, this would be before appInsights is configured at all, giving you no chance to disable the patching. Definitely open to ideas on how this could be made better!

**Comment by MSLaguana** [comment]
Yeah, @OsvaldoRosado points out the issue here.

@jeffwilcox would you be happy if you had to write your code like this:

```js
const appInsights = require("applicationinsights");
appInsights.setAutoCollectDiagnosticChannels(true); // or pass in a list of things to augment, or something

const restOfApplication = require("...");

restOfApplication.start()
```

That is, if you had to require and configure application insights as the very first thing in your application, before requiring anything else?

The other complicating factor is that the patches we apply are required for the correct working of automatic correlation. If you disable one of the modules that we patch, then we can't guarantee that any of the AI events will be correctly associated with the right request. For example, if you disable patching mongodb, then the following code may not work correctly:

```js
var appInsights = require("applicationinsights");
/*... configure appInsights */
var mongodb = require('mongodb');

mongodb.MongoClient.connect("...", function (err, db) {
  const collection = db.collection("documents")

  var server = http.createServer((req, res) => {
    collection.findOne({id: req.query.id}, function (err, item) {
      appInsights.client.trackTrace("Responding to query " + req.query.id + " with " + JSON.stringify(item));
      res.end(JSON.stringify(item));
    }
  });

});
```

Due to how mongo behaves internally, if multiple HTTP requests come in at a similar time, the mongo queries that they trigger can be batched together. This means that at least one callback where `trackTrace` is invoked will end up with mismatched information about the request it is part of, so you might see one request having two different traces associated with it, or potentially all the traces may be associated with no HTTP request.

The current approach where we enable our patches by default is an attempt to have things "just work" as much as possible, and the environment variables are there as a way to disable it if necessary but hopefully not without being aware of the consequences. If we do change to a configured-opt-in approach there are more opportunities for accidental mis-configurations and confusing errors if things aren't done in just the right order.

**Comment by AlexBulankou** [comment]
Looks like current solution (other than using env variables) is to complete initialization before calling ``require`` on all libraries that might be impacted, such as mongodb in above example.
