### ISSUE TITLE
Has Application Insights REST Api been implemented?

### ISSUE THREAD

**Issue by CallumBrankin** [Microsoft/ApplicationInsights-node.js#293]
I'm wondering if the [Application Insights REST Api](https://dev.applicationinsights.io) has been implemented into ApplicationInsights-node.js?

**Comment by OsvaldoRosado** [comment]
The REST API methods have not been implemented in this SDK. Our SDKs are intended for instrumentation of your server code with Application Insights telemetry collection, rather than telemetry retrieval.

If you think a dedicated client for accessing the REST API would be useful, feel free to share this via UserVoice at https://feedback.azure.com/forums/357324-application-insights/category/161985-api
