### ISSUE TITLE
Node.JS SDK stable 1.0 release plan

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-node.js#297]
Tentative timeline:
* 0.22 release: 8/31/2017
  * [Bug fixes for 0.22](https://github.com/Microsoft/ApplicationInsights-node.js/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A0.22.0)
  * Reliable storage-backed retry logic for all error codes, enabling by default
  * API cleanup and telemetry processor refactoring
  * Analyzing customer telemetry
  * Automated functional tests - to verify that expected telemetry is generated
* 0.23 release: 9/15/2017
  * [Bug fixes for 0.23](https://github.com/Microsoft/ApplicationInsights-node.js/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A0.23.0)
  * Finalize which performance counters are recorded and at what names
  * Ensure official docs.microsoft.com entries exist
  * Running performance tests **manually** to establish baseline. This does not create automated solution.
  * Analyzing customer telemetry
* 1.0 release: 9/29/2017
  * Stabilization, critical bug fixes from 0.23

@OsvaldoRosado, thoughts on this? I am thinking we can release stable Node.JS without automated performance tests. However we do need automated functional tests to verify that expected telemetry is generated.

**Comment by OsvaldoRosado** [comment]
This makes sense to me. When building automated funcs, we should consider making it easily referenced by https://github.com/Microsoft/node-diagnostic-channel . That way we can have iterations on the autocollection patches there with the safety of knowing they likely don't break AI.

**Comment by SergeyKanzhelev** [comment]
I'm interested in "API cleanup and telemetry processor refactoring" work item. Will you track work as a separate issue?

**Comment by AlexBulankou** [comment]
We can just track it here - I'll list these details above. @SergeyKanzhelev, @OsvaldoRosado, @joshgav, what are your current top issues with the Node.JS API?

**Comment by SergeyKanzhelev** [comment]
""One of the problem"" with initializers and processors in `node.js` and `javascript` for me is lack of strong typing. So you can add a processor, but you cannot remove or change configuration for one of pre-defined one. I believe it will be great to move the most of enrichment logic like setting operation ID, user ID and such into initializers. So one can disable processor instead of adding property to the global configuration. Perhaps processor returns it's name or store name-processor pairs instead of processors list?

**Another problem** is that you cannot create an alternative pipeline with the different set of processors (as I understand). It will be great to allow creating client that do not have sampling processor defined.

**Third** need to document what exactly context may contain and when it will or will not have certain fields. Current documentation mentions what can be passed in there, but have no clarifications on when and why. Also need to have docs on how one can pass another piece of configuration into the processor. Perhaps whatever diagnostics channel has should be passed to processors in context?

Talking about diagnostics channel - need to document how to listen for it to support new libraries monitoring. Ideally have a generic listener for everything channel exposes and allow customers to adjust monitoring (using processors?). Some example code would be helpful.



From public API perspective - we pass an envelope to the processor which binds schema very tightly to implementation. In C# we have an indirection level. Maybe the same indirection level may be helpful in `node.js`. 

Also since you working on channel improvements - maybe channel configuration may be moved to some "Channel" class. So one can implement an alternative telemetry "sink". Example may be very short living process that needs to send data synchronously. Or stdout output channel for containers

**Comment by AlexBulankou** [comment]
@SergeyKanzhelev breaking down your suggestions into items:

1. Refactor internal tagOverride objects into standard telemetry initializers and allow disabling/modifying standard telemetry initializers. I believe this is item **is NOT required for stable**.
2. Allow sending telemetry with custom sampling configuration and custom set of telemetry processors. I believe this item is *required for stable*
3. Document internal fields population. *Required for stable milestone, but not prerequisite to release*
4. Document diagnostic channel. *Required for stable milestone, but not prerequisite to release*
4. Decouple envelope shape from telemetry processor API, don't expose envelope to processors. *NOT  required for stable*
5. Enable and document custom telemetry senders, a.k.a. custom channels. This is an enhancement, *NOT required for stable*

Thoughts on the breakdown?

Another item related to 1 and 2 is whether userId and sessionId enrichment should be part of correlation context and thus automatically apply to any manually-collected telemetry. Today it does not, and I think this is a serious omission.

**Comment by OsvaldoRosado** [comment]
I believe the second item there works today. Yes, you cannot remove the sampling telemetry processor, but if you in your own telemetry processor set the sample rate to 0, the sampling telemetry processor will detect this and do nothing.

**Comment by SergeyKanzhelev** [comment]
I'd really like to see SDK moving into modular and replaceable approach. Like mentioned in this issue https://github.com/Microsoft/ApplicationInsights-JS/issues/502.

As example, entire userid sessionid logic should be a module of sort that can be configured (do not use cookies), disabled and replaced from one place, not from the global config. Ideally it should be a telemetry processor that I can find, configure, remove or add another processor in front of it.

I'm fine if not all the problems will be addressed in this release. I just suggest to think what can be addressed now. So I'm fine with your assessment

**Comment by yoadsn** [comment]
Hi guys, thanks for this work.
Are you planning on releasing 0.22 or the plans have changed?
Since this is a breaking change (client API surface changes) would love to go with the new API for new developments...

**Comment by OsvaldoRosado** [comment]
We are planning on releasing 0.22, but as a combined release with what was planned code-wise for 0.23. The new ETA for 0.22 being ready is by the end of the week.
