### ISSUE TITLE
Client for consuming metrics/events etc ? 

### ISSUE THREAD

**Issue by vladbarosan** [Microsoft/ApplicationInsights-node.js#350]
Is there a reason why there is no client for consuming metrics once they are sent to App Insights via a `track*` call?

E.g.  Querying aggregations for an event or a metric

**Comment by OsvaldoRosado** [comment]
Are you looking for something to pull your telemetry from Application Insights? Or rather some kind of callback to use locally on the track methods?

If the former, there's a simple REST API at https://dev.applicationinsights.io/ that you can use to consume this data. This SDK does not implement this API as it's intended use is for server instrumentation rather than data retrieval.

If you think a dedicated client for accessing the REST API would be useful, feel free to share this via UserVoice at https://feedback.azure.com/forums/357324-application-insights/category/161985-api

**Comment by vladbarosan** [comment]
@OsvaldoRosado yes a client for pulling telemetry.
I created this item here:
 https://feedback.azure.com/forums/357324-application-insights/suggestions/32214247-implement-support-for-querying-telemetry-in-sdk-s 

you mentioned UserVoice but that is an azure feedback link. Let me know if I should create the item in UserVoice somewhere.

**Comment by OsvaldoRosado** [comment]
Sorry, it's just a rename of the service 😄 The Azure feedback site is our UserVoice.

Thanks for making the item!

Closing this for now, feel free to re-open if necessary.
