### ISSUE TITLE
Guidance to manage async call to appInsights.track*

### ISSUE THREAD

**Issue by v-geberr** [Microsoft/ApplicationInsights-node.js#361]
What is the suggested method to manage the asynchronous nature of the appInsights.track* calls? They are not typical callback/promise so there is no way to know how or when they will return.

**Comment by OsvaldoRosado** [comment]
This isn't something this SDK exposes to end users, at least not on a specific telemetry item basis. 

This SDK will manage reliable transmission of your telemetry item, but makes no promises as to when. Telemetry items get batched and sent together at regular intervals (or when the maximum batch size is met). If telemetry transmission fails, the payload is stored to disk and retried again later. Because we can retry later from disk, it's entirely possible that the track call won't actually make it to the backend until another run of the application (in the case of our service being down or network errors connecting to it from the client end). Beyond retry logic and connectivity issues, there's non-failure scenarios where your item will not be sent as well (such as sampling rate being set to lower than 100%).

If it is critical for your application to control the sending of telemetry, you could use the following to force items be sent immediately, and be told when this completes:

```
client.track...
client.flush({callback: (responseFromAppInsights) => {

}});
```

This flush call still has the potential to be batched. If you want to force purely serial transmission you can use the following:

```
client.config.maxBatchSize = 1;
```

**Comment by OsvaldoRosado** [comment]
Closing this. Please feel free to reopen if the above didn't answer your question!
