### ISSUE TITLE
ApplicationInsights:Sender [ 'Error while saving data to disk: Setting ACL restrictions did not succeed (ICACLS returned code 1332)' ]

### ISSUE THREAD

**Issue by snrao310** [Microsoft/ApplicationInsights-node.js#375]
We are using the Application Insights with our node application and quite frequently get this error ( approximately every 5 min). When the error occurs, the whole app seems to restart. It is unclear if the error is in some way fatal.

**Comment by OsvaldoRosado** [comment]
This error isn't fatal, but indicates that the SDK was unable to protect the directory it uses to store telemetry that failed to send for retrying at a later time. This is important because your telemetry may contain sensitive information and we wouldn't want to expose this data to other users on your machine. When this scenario happens, the SDK logs the error to let you know, and doesn't store the failed telemetry to disk.

That saving to disk is being attempted every 5 mins indicates your app is having trouble connecting to the Internet or at least connecting to the Application Insights telemetry ingestion endpoint.

I'm not sure what is the exact cause of error 1332, but essentially any errors from ICACLS means Windows had a problem setting folder permissions. Some searches online say this particular error might be related to incorrect group policy settings.

Regardless, this particular error shouldn't cause your app to restart. Since storing to disk is failing anyway you can disable the entire feature with the `setUseDiskRetryCaching(false)` method chained to your call to `setup()`. That should let you further pinpoint where the restarting is coming from.

**Comment by snrao310** [comment]
Thanks a lot. I set the disk retry caching to false.

**Comment by OsvaldoRosado** [comment]
Closing this for now. Feel free to reopen if there are more related issues!

**Comment by przemos** [comment]
would it be fair to say ICACLS "warning" should generate a telemetry with severityLevel = 2 (warning)?
