### ISSUE TITLE
How do I relate telemetry produced by processing a request?

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/ApplicationInsights-node.js#388]
Hi,

I'm looking for some guidance / best practices for how to use `TelemetryClient`. My goal is to track and relate all telemetry for a given request, so it can be analyzed as a "package" of telemetry in the portal. 

I'm noticing my Request and Exception telemetry are not related in the portal for example. My request has an operationId, but the Exception has none; this makes them appear unrelated even though they were tracked while processing the same server request.

To be more specific, here's how I'm setting up my logging and tracking requests, exceptions, etc:

1. At application startup, I create a `TelemetryClient` instance with my iKey and persist it for the lifetime of the application.
2. As requests come in, the first item of business is to call `trackNodeHttpRequest`. This results in a Request telemetry record in the portal with an OperationId.
3. As further business logic processes the request, I call `trackException`, which results in an Exception telemetry record in the portal with no OperationId.

Based on the answer to https://github.com/Microsoft/ApplicationInsights-node.js/issues/37, I am led to believe a new instance of `TelemetryClient` should be used for every request, so that OperationId can be assigned on the client and used across all telemetry tracking calls. However, this also seems very manual and what the Application Insights library was trying to solve by use of "auto" settings.

Reflecting on this all more, I guess it makes sense that the client doesn't know my telemetry is related because I haven't passed any data to relate the the multiple `track<blah>` invokes. So how can I accomplish what I'm after?

Sorry if this has been asked, or is in documentation somewhere already; it likely is since it's a basic scenario, but I couldn't find it and I'm lost for getting this working.

Thanks.

**Comment by OsvaldoRosado** [comment]
Are you disabling automatic correlation when initializing the SDK? It should be doing this work for you. It sounds like you might be skipping SDK initialization as you directly create a `TelemetryClient` instance rather than using `appInsights.setup().start()` and `appInsights.defaultClient`.

Another thing to look for is to make sure this SDK is the first require you do in your code. It's very important as correlation between requests/dependencies/exceptions/etc. requires patching of require itself (as well as a bunch of other stuff that needs to be patched before anything else can call them).

Some other questions:
- Which version of Node are you on? Automatic correlation only works on versions > 3.3
- What kind of asynchronous code do you use? Automatic correlation does not yet work with native async/await (but is totally fine with async/await transpiled down into promises)
- Do you call `trackNodeHttpRequest` because automatic request collection does not work, or simply because you choose not to? If it doesn't work, it may imply a deeper issue that is also impacting the patches that start new automatic correlation contexts that happen in the same area of SDK code.
  - This might also be related to not calling `appInsights.setup().start()` and instead creating a manual `TelemetryClient`

As for
> Based on the answer to #37, I am led to believe a new instance of TelemetryClient should be used for every request

This is not suggested and is simply old advice from many years ago 😃. Thankfully you don't have to do it this way anymore!

If automatic correlation cannot be made to work, operation_Id should be assigned using the `tagOverrides` property accepted by every `track<>` call in `TelemetryClient`. This is important assuming you have asynchronous code, as it will otherwise be tricky to track what the correct reference to `TelemetryClient` is without having to pass it around everywhere. Making a new instance each time will also incur extra overhead in memory and network from the extra classes and lack of central batching of telemetry items.

**Comment by OsvaldoRosado** [comment]
Thanks for the answers!

> No, I am using the default settings, which is enabled automatic correlation if I'm not mistaken. Also, I am calling appInsights.setup(iKey) and then using the appInsights.defaultClient instance of TelemetryClient across the application. I'm not calling new TelemetryClient() anywhere.

Great! I was just confused by `I create a TelemetryClient instance`. To be clear, you also call `.start()` after `.setup(iKey)` correct? `.start()` is responsible for starting autocollection and autocorrelation.

> I'm using trackNodeHttpRequest because I thought it was the recommended way to track requests to completion. Are you implying that automatic request tracking was working in my application as intended, I wouldn't need to call trackNodeHttpRequest nor trackRequest?

That's correct. In the following sample app (not tested code but right idea), both requests and dependencies should be collected on your behalf automatically. If you don't see the same behavior when using this SDK in your project, that's a great starting point for debugging the correlation issues!

```
let appInsights = require("applicationinsights");
let http = require('http');
appInsights.setup(iKey).start();

http.createServer((req, res) => {
   let data = '';
   http.get('http://bing.com', (resp) => {
      resp.on('data', (d) => data += d);
      resp.on('end', () => res.end(data));
   });
});
```

**Comment by scott-lin** [comment]
Well, thank you for asking about `start()` missing! How embarrassing. 😄 Somewhere along the line, I removed that, forgot to put it back, and never noticed it when double checking the documented samples. 

Thanks for your time and pointers on other areas of the library. I've confirmed requests are magically tracked without calling `trackNodeHttpRequest` -- very cool and convenient library!
