### ISSUE TITLE
ApplicationInsights blocks scripts from exiting

### ISSUE THREAD

**Issue by richardspence** [Microsoft/ApplicationInsights-node.js#390]
I'm using application insights to instrument a gulp build script, and it blocks gulp from exiting when started.  

I manually need to run `client.dispose()` after each entry task's exit point (on finish, on error) and the error handlers of all the dependencies.

I'm guessing the architecture has a log collector agent that is running in the background.  It would be good to have a synchronous mode where that's not created, and flush the events on process exit.

**Comment by OsvaldoRosado** [comment]
As an extra note, it's definitely a bug if this SDK keeps you from exiting after all batched items have been sent (when no extra collection features are enabled), rather than a missing mode. This should be covered in this test, but perhaps it's missing something:

https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Tests/js/endToEnd.js

**Comment by richardspence** [comment]
Yes I was using `client.start()` as I thought it was required.

Changing my configuration to this, solves my issue:
```js
const appInsights = require('applicationinsights');
appInsights.setup("...")
    .setAutoCollectExceptions(true)
    .setAutoCollectConsole(true)

appInssights.defaultClient.config.maxBatchIntervalMs = 100;
```

Thanks!
