### ISSUE TITLE
userAgent not tracked

### ISSUE THREAD

**Issue by yoadsn** [Microsoft/ApplicationInsights-node.js#393]
I have looked at the code and could see the userAgent is parsed from the request. (stored on `this`)

Though, this information is never provided with the tracked request under the `ai.user.userAgent` key and so the client_Browser field is empty with all our auto-tracked requests.

Seems like this is by design, is that so? Why?

**Comment by SergeyKanzhelev** [comment]
I'm closing this issue for now. Please re-open if you need more details or some help implementing telemetry processor.

**Comment by goto1** [comment]
@SergeyKanzhelev is there a way to populate the `client_Browser` field if I extract this information myself instead of passing the entire `User-Agent` string? It does look like I can add this information in a custom property but sometimes custom properties do not appear everywhere I would like them to appear, e.g. in filters or certain views.

Any help would be appreciated, thanks!

**Comment by SergeyKanzhelev** [comment]
@goto1 I'm not working on Application Insights any longer and not sure if there were any changes. Also it seems that the events schema was moved some place I'm not aware of. Maybe @ramthi can help?
