### ISSUE TITLE
Error when running in electron

### ISSUE THREAD

**Issue by JontyMC** [Microsoft/ApplicationInsights-node.js#419]
I can't get application insights to work in my electron app. When I run the app, I get this:

ApplicationInsights:CorrelationIdManager [ { Error: connect ECONNREFUSED 127.0.0.1:443
      at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError
      at AppInsightsAsyncCorrelatedErrorWrapper
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443 } ]

Any ideas?

**Comment by JontyMC** [comment]
I hadn't overridden any config. Strangely, it just started working.

**Comment by OsvaldoRosado** [comment]
Glad to hear its working! 

I'd be especially suspicious of environment variables - in particular the non-AI specific `http_proxy`/`https_proxy` variables since the behavior changed without changing the app itself - and you have no overrides for the AI SDK. If it reproduces again, I'd highly suggest getting a snapshot of the current env vars!

It might also be a good idea to use `setInternalLogging(true, true)` before calling `start()` on the `appInsights` object. This might emit helpful debugging information.
