### ISSUE TITLE
Custom dimensions are truncated to the wrong limit

### ISSUE THREAD

**Issue by OsvaldoRosado** [Microsoft/ApplicationInsights-node.js#444]
See report at: https://stackoverflow.com/questions/52973839/nodejs-application-insigths-string-property-suddenly-limited-to-1024

https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Util.ts#L13 sets the limit for custom dimension properties values to length 1024. However, the limit specified in the schema is 8192 (see https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/EventData.bond#L19)

**Comment by sean-mcmanus** [comment]
We hit this bug too after upgrading from 1.0.5 to 1.0.6 (https://github.com/Microsoft/vscode-cpptools/issues/2587).

**Comment by ramya-rao-a** [comment]
@OsvaldoRosado Can you post an update here when a new version is released?

**Comment by OsvaldoRosado** [comment]
@ramya-rao-a Will do

**Comment by ramya-rao-a** [comment]
@OsvaldoRosado What is the current plan for the next release? 

Due to this issue, the C++ extension had to revert back to the older version which had the spawning powershell problem

So either we need to have a new version of the applicationInsights or the C++ extension will have to go back to an even older version of applicationInsights.

**Comment by ramya-rao-a** [comment]
Thanks @OsvaldoRosado 

@sean-mcmanus also mentioned that he needs more time to release a new version due to major changes in the master branch. Therefore, the current plan is to point the C++ extension users to an older version of the extension.

Thanks for all the help on this.

**Comment by ramya-rao-a** [comment]
Thanks!
