### ISSUE TITLE
Custom telemetry not being linked to request in Azure Functions

### ISSUE THREAD

**Issue by HShather** [Microsoft/ApplicationInsights-node.js#484]
We are using Azure functions version ~2 and writing http triggers in javascript

Custom telemetry written using the operation.id  is no longer linked to the original request, it was previously (December last year)

Following the code in this documentation
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#custom-telemetry-in-javascript-functions

```
const appInsights = require("applicationinsights");
appInsights.setup();
const client = appInsights.defaultClient;

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    client.trackEvent({name: "my custom event", tagOverrides:{"ai.operation.id": context.invocationId}, properties: {customProperty2: "custom property value"}});
    client.trackException({exception: new Error("handled exceptions can be logged with this method"), tagOverrides:{"ai.operation.id": context.invocationId}});
    client.trackMetric({name: "custom metric", value: 3, tagOverrides:{"ai.operation.id": context.invocationId}});
    client.trackTrace({message: "trace message", tagOverrides:{"ai.operation.id": context.invocationId}});
    client.trackDependency({target:"http://dbname", name:"select customers proc", data:"SELECT * FROM Customers", duration:231, resultCode:0, success: true, dependencyTypeName: "ZSQL", tagOverrides:{"ai.operation.id": context.invocationId}});
    client.trackRequest({name:"GET /customers", url:"http://myserver/customers", duration:309, resultCode:200, success:true, tagOverrides:{"ai.operation.id": context.invocationId}});

    context.done();
};
```

What we see in appinsights is that the custom telemetry is linked together but none of the custom events are linked back to the original request. 
Is this an sdk issue or functions issue?

![image](https://user-images.githubusercontent.com/38656315/52702021-bffca800-2f7b-11e9-8c65-9631adfee43e.png)

![image](https://user-images.githubusercontent.com/38656315/52702144-ff2af900-2f7b-11e9-93ce-d23a6a5ed331.png)

**Comment by OsvaldoRosado** [comment]
I believe this is being tracked here: https://github.com/Azure/azure-functions-host/issues/3747

You're running into an issue specific to Functions v2, if you were to go back to v1 you wouldn't run into this behavior. 

The basic root cause is that invocationid is no longer the operation id used for telemetry collected by the Functions runtime. Beyond that, the value that Functions is using for the operation id in v2 is seemingly not available to non-.NET functions.

Until the issue linked above is resolved, I don't believe there's a way to have functioning linking of custom telemetry and Functions-generated telemetry in Functions v2.

/cc: @lmolkova

**Comment by HShather** [comment]
Thanks for the quick response. we can close this now
in general the function v2 and app insights experience is not the best currently
there is also this issue which prevents correct response codes being logged in AI
https://github.com/Azure/azure-functions-host/issues/2447
