### ISSUE TITLE
Multiple identical messages generated for a single log call

### ISSUE THREAD

**Issue by bigman73** [microsoft/ApplicationInsights-node.js#563]
When running a mocha test with a single logger.info call that produces 4 identical logs messages in App Insights, instead of 1.

The logger is initialized only once.

 "applicationinsights": "^1.5.0"

I noticed a similar issue reported for ApplicationInsights-JS: https://stackoverflow.com/questions/54929563/azure-application-insights-shows-the-same-event-at-identical-timestamps-multiple

Any ideas?

**Comment by markwolff** [comment]
Which logger are you using?

**Comment by bigman73** [comment]
The logger is winston-azure-application-insights

Oddly enough the problem happens when running the mocha tests from terminal
Running mocha tests from VS.Code works as expected

**Comment by markwolff** [comment]
A couple of things here
- VSCode is instrumented with SDK, but disables some of the patching we do. They do this via setting an environment variable which gets passed down to all child processes spawned via it (e.g. you using their integrated terminal!) See the resolution to #560
- This SDK automatically patches winston for you (outside of VSCode!) and sends logs from it. See https://github.com/microsoft/applicationinsights-node.js#automatic-third-party-instrumentation
- The winston-azure-application-insights package is not something that was made/supported by us. Since this SDK natively supports winston3, I don't think there is much purpose to using that package anymore, so you should prefer just using this SDKs automatic patching for winston.

**Comment by bigman73** [comment]
Thanks for the info.
The usage of winston in our application is dual - either appinsights or standard file/console transports.
If winston-azure-application-insights is removed then how would you recommend to add an appinsights transport? 
The automatic patching will get it done?
To disable appinsights (leave file/console transports) simply set the env var APPLICATION_INSIGHTS_NO_PATCH_MODULES=winston?

**Comment by markwolff** [comment]
[The patching we do](https://github.com/microsoft/node-diagnostic-channel/blob/a2790ca5e762e550010493fc91b92ec754a7a75e/src/diagnostic-channel-publishers/src/winston.pub.ts#L46) is basically adding an app insights transport to your winston instance for you. It shouldn't interfere with existing file/console transports AFAIK, but yes you can disable our patching in that way.

**Comment by bigman73** [comment]
Thanks, I will try removing the 3rd party module and testing

**Comment by markwolff** [comment]
Closing this for now since there seems to be some dual instrumentation involved. Comment here if its still an issue and I'll reopen this
