### ISSUE TITLE
Filtering Microsoft.ServiceBus.Messaging.MessagingEntityNotFoundException in FunctionApp 

### ISSUE THREAD

**Issue by kevinp** [microsoft/ApplicationInsights-node.js#729]
We provision our Service Bus message queues on-demand when a client sends a message to a given queue.  This means that when our service bus triggered functions are deployed, the queues they listen on may or may not be available yet.  If the queues are not available, the ServiceBus assembly generates the following exception every second or so:

> Message processing error (Action=Receive, ClientId=MessageReceiver3integrations-xxx-xxx-xxx, EntityPath=integrations-xxx-xxx-xxx, Endpoint=xxx-xxx-xxx.servicebus.windows.net)        
> [2021-02-10T20:13:25.499Z] Microsoft.Azure.ServiceBus: Put token failed. status-code: 404, status-description: The messaging entity 'sb://xxx-xxx-xxx.servicebus.windows.net/integrations-xxx-xxx-xxx' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:2c8908cf-e44a-4ede-a669-ece899d3a46e_G11, SystemTracker:xxx-xxx-xxx.servicebus.windows.net:integrations-xxx-xxx-xxx, Timestamp:2021-02-10T20:13:25.

We would like to filter out these exceptions.  It seems like a good job for a telemetry processor, but these exceptions are being thrown by the host before our application code is called.

I know I can filter exceptions from the host.json file, but I don't see a way to filter based on assembly or exception type.  We assume there may be host exceptions we'd want know about.

Would you be able to recommended an approach to filtering these exceptions?  

Thanks for your help!

**Comment by hectorhdzg** [comment]
@kevinp like you mentioned the way to handle filtering of telemetry is through telemetry processors, sounds like Application Insights node.js SDK is not the one sending the exception telemetry because your app code is not called yet and most likely the SDK sending exception telemetry is .NET SDK running on IIS, you must be able to confirm looking at the SDK version property in the telemetry, if telemetry is coming from .NET would be good to file the issue in their repo so the appropriate people can help.

**Comment by kevinp** [comment]
Thanks!  I've confirmed that sdkVersion = azurefunctions: 3.0.15193.0.  I will post there.  👍
